In [2]:
import pandas as pd

In [3]:
weather_df = pd.read_csv('Data/weather_data_skopje_2022_to_2024.csv')

In [4]:
df_pm10 = pd.read_csv('Data/pm10_data_cleaned.csv')
df_pm2_5 = pd.read_csv('Data/pm2_5_data_cleaned.csv')
df_no2 = pd.read_csv('Data/no2_data_cleaned.csv')

In [6]:
df_pm10['timestamp'] = pd.to_datetime(df_pm10[['year', 'month', 'day', 'hour']].apply(lambda x: x.astype(str).str.zfill(2)).agg('-'.join, axis=1))

In [8]:
df_pm2_5['timestamp'] = pd.to_datetime(df_pm2_5[['year', 'month', 'day', 'hour']].apply(lambda x: x.astype(str).str.zfill(2)).agg('-'.join, axis=1))
df_no2['timestamp'] = pd.to_datetime(df_no2[['year', 'month', 'day', 'hour']].apply(lambda x: x.astype(str).str.zfill(2)).agg('-'.join, axis=1))

In [11]:
weather_df['timestamp'] = pd.to_datetime(weather_df['stamp'])

In [13]:
weather_df.drop(columns=['stamp'], inplace=True)

In [14]:
weather_df.head(10)

   temperature  humidity  wind_speed           timestamp
0          5.9        79         2.6 2022-01-01 00:00:00
1          5.8        78         0.8 2022-01-01 01:00:00
2          6.0        77         2.6 2022-01-01 02:00:00
3          6.4        74         5.1 2022-01-01 03:00:00
4          6.3        74         2.1 2022-01-01 04:00:00
5          6.0        76         2.9 2022-01-01 05:00:00
6          5.6        77         1.9 2022-01-01 06:00:00
7          6.0        74         5.2 2022-01-01 07:00:00
8          7.9        73         2.6 2022-01-01 08:00:00
9         11.1        69         2.3 2022-01-01 09:00:00

In [21]:
df_pm10.head(30)

,date,sensor_id,hour,type,value,year,month,day,timestamp
0,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,1,pm10,47,2022,1,1,2022-01-01 01:00:00
1,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,2,pm10,69,2022,1,1,2022-01-01 02:00:00
2,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,3,pm10,100,2022,1,1,2022-01-01 03:00:00
3,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,4,pm10,70,2022,1,1,2022-01-01 04:00:00
4,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,5,pm10,59,2022,1,1,2022-01-01 05:00:00
5,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,6,pm10,65,2022,1,1,2022-01-01 06:00:00
6,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,7,pm10,62,2022,1,1,2022-01-01 07:00:00
7,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,8,pm10,64,2022,1,1,2022-01-01 08:00:00
8,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,9,pm10,69,2022,1,1,2022-01-01 09:00:00
9,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,10,pm10,77,2022,1,1,2022-01-01 10:00:00
10,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,11,pm10,55,2022,1,1,2022-01-01 11:00:00
11,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,12,pm10,51,2022,1,1,2022-01-01 12:00:00
12,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,13,pm10,11,2022,1,1,2022-01-01 13:00:00
13,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,14,pm10,7,2022,1,1,2022-01-01 14:00:00
14,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,15,pm10,9,2022,1,1,2022-01-01 15:00:00
15,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,16,pm10,6,2022,1,1,2022-01-01 16:00:00
16,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,17,pm10,8,2022,1,1,2022-01-01 17:00:00
17,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,18,pm10,9,2022,1,1,2022-01-01 18:00:00
18,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,19,pm10,27,2022,1,1,2022-01-01 19:00:00
19,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,20,pm10,15,2022,1,1,2022-01-01 20:00:00
20,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,21,pm10,27,2022,1,1,2022-01-01 21:00:00
21,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,22,pm10,29,2022,1,1,2022-01-01 22:00:00
22,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,23,pm10,22,2022,1,1,2022-01-01 23:00:00
23,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,1,pm10,234,2022,1,1,2022-01-01 01:00:00
24,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,2,pm10,315,2022,1,1,2022-01-01 02:00:00
25,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,3,pm10,282,2022,1,1,2022-01-01 03:00:00
26,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,4,pm10,197,2022,1,1,2022-01-01 04:00:00
27,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,5,pm10,205,2022,1,1,2022-01-01 05:00:00
28,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,6,pm10,151,2022,1,1,2022-01-01 06:00:00
29,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,7,pm10,170,2022,1,1,2022-01-01 07:00:00

In [20]:
df_pm2_5.head(30)

,date,sensor_id,hour,type,value,year,month,day,timestamp
0,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,1,pm25,40,2022,1,1,2022-01-01 01:00:00
1,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,2,pm25,65,2022,1,1,2022-01-01 02:00:00
2,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,3,pm25,83,2022,1,1,2022-01-01 03:00:00
3,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,4,pm25,59,2022,1,1,2022-01-01 04:00:00
4,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,5,pm25,56,2022,1,1,2022-01-01 05:00:00
5,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,6,pm25,62,2022,1,1,2022-01-01 06:00:00
6,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,7,pm25,58,2022,1,1,2022-01-01 07:00:00
7,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,8,pm25,52,2022,1,1,2022-01-01 08:00:00
8,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,9,pm25,60,2022,1,1,2022-01-01 09:00:00
9,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,10,pm25,63,2022,1,1,2022-01-01 10:00:00
10,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,11,pm25,45,2022,1,1,2022-01-01 11:00:00
11,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,12,pm25,41,2022,1,1,2022-01-01 12:00:00
12,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,13,pm25,5,2022,1,1,2022-01-01 13:00:00
13,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,14,pm25,4,2022,1,1,2022-01-01 14:00:00
14,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,15,pm25,4,2022,1,1,2022-01-01 15:00:00
15,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,16,pm25,3,2022,1,1,2022-01-01 16:00:00
16,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,17,pm25,4,2022,1,1,2022-01-01 17:00:00
17,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,18,pm25,6,2022,1,1,2022-01-01 18:00:00
18,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,19,pm25,23,2022,1,1,2022-01-01 19:00:00
19,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,20,pm25,11,2022,1,1,2022-01-01 20:00:00
20,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,21,pm25,19,2022,1,1,2022-01-01 21:00:00
21,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,22,pm25,26,2022,1,1,2022-01-01 22:00:00
22,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,23,pm25,13,2022,1,1,2022-01-01 23:00:00
23,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,1,pm25,128,2022,1,1,2022-01-01 01:00:00
24,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,2,pm25,178,2022,1,1,2022-01-01 02:00:00
25,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,3,pm25,150,2022,1,1,2022-01-01 03:00:00
26,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,4,pm25,109,2022,1,1,2022-01-01 04:00:00
27,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,5,pm25,116,2022,1,1,2022-01-01 05:00:00
28,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,6,pm25,84,2022,1,1,2022-01-01 06:00:00
29,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,7,pm25,85,2022,1,1,2022-01-01 07:00:00

In [16]:
weather_df = weather_df[weather_df['timestamp'].dt.hour != 0]

In [22]:
weather_df

       temperature  humidity  wind_speed           timestamp
1              5.8        78         0.8 2022-01-01 01:00:00
2              6.0        77         2.6 2022-01-01 02:00:00
3              6.4        74         5.1 2022-01-01 03:00:00
4              6.3        74         2.1 2022-01-01 04:00:00
5              6.0        76         2.9 2022-01-01 05:00:00
...            ...       ...         ...                 ...
25435          3.1        52         3.1 2024-11-25 19:00:00
25436          2.8        52         2.2 2024-11-25 20:00:00
25437          2.2        54         2.7 2024-11-25 21:00:00
25438          1.8        56         2.9 2024-11-25 22:00:00
25439          1.4        57         3.2 2024-11-25 23:00:00

[24380 rows x 4 columns]

In [23]:
df_pm10_merged = pd.merge(df_pm10, weather_df, on='timestamp', how='left')
df_pm2_5_merged = pd.merge(df_pm2_5, weather_df, on='timestamp', how='left')
df_no2_merged = pd.merge(df_no2, weather_df, on='timestamp', how='left')

In [24]:
df_pm10_merged.head(30)

,date,sensor_id,hour,type,value,year,month,day,timestamp,temperature,humidity,wind_speed
0,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,1,pm10,47,2022,1,1,2022-01-01 01:00:00,5.8,78.0,0.8
1,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,2,pm10,69,2022,1,1,2022-01-01 02:00:00,6.0,77.0,2.6
2,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,3,pm10,100,2022,1,1,2022-01-01 03:00:00,6.4,74.0,5.1
3,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,4,pm10,70,2022,1,1,2022-01-01 04:00:00,6.3,74.0,2.1
4,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,5,pm10,59,2022,1,1,2022-01-01 05:00:00,6.0,76.0,2.9
5,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,6,pm10,65,2022,1,1,2022-01-01 06:00:00,5.6,77.0,1.9
6,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,7,pm10,62,2022,1,1,2022-01-01 07:00:00,6.0,74.0,5.2
7,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,8,pm10,64,2022,1,1,2022-01-01 08:00:00,7.9,73.0,2.6
8,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,9,pm10,69,2022,1,1,2022-01-01 09:00:00,11.1,69.0,2.3
9,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,10,pm10,77,2022,1,1,2022-01-01 10:00:00,13.4,64.0,3.3
10,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,11,pm10,55,2022,1,1,2022-01-01 11:00:00,15.2,58.0,4.4
11,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,12,pm10,51,2022,1,1,2022-01-01 12:00:00,15.1,54.0,3.1
12,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,13,pm10,11,2022,1,1,2022-01-01 13:00:00,14.8,65.0,4.6
13,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,14,pm10,7,2022,1,1,2022-01-01 14:00:00,12.4,70.0,6.5
14,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,15,pm10,9,2022,1,1,2022-01-01 15:00:00,8.4,73.0,10.1
15,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,16,pm10,6,2022,1,1,2022-01-01 16:00:00,7.7,70.0,9.7
16,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,17,pm10,8,2022,1,1,2022-01-01 17:00:00,7.0,72.0,10.1
17,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,18,pm10,9,2022,1,1,2022-01-01 18:00:00,8.5,66.0,8.7
18,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,19,pm10,27,2022,1,1,2022-01-01 19:00:00,8.9,66.0,7.6
19,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,20,pm10,15,2022,1,1,2022-01-01 20:00:00,6.3,77.0,8.4
20,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,21,pm10,27,2022,1,1,2022-01-01 21:00:00,5.6,80.0,8.4
21,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,22,pm10,29,2022,1,1,2022-01-01 22:00:00,4.5,85.0,8.6
22,2022-01-01,01440b05-255d-4764-be87-bdf135f32289,23,pm10,22,2022,1,1,2022-01-01 23:00:00,4.7,86.0,8.3
23,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,1,pm10,234,2022,1,1,2022-01-01 01:00:00,5.8,78.0,0.8
24,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,2,pm10,315,2022,1,1,2022-01-01 02:00:00,6.0,77.0,2.6
25,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,3,pm10,282,2022,1,1,2022-01-01 03:00:00,6.4,74.0,5.1
26,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,4,pm10,197,2022,1,1,2022-01-01 04:00:00,6.3,74.0,2.1
27,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,5,pm10,205,2022,1,1,2022-01-01 05:00:00,6.0,76.0,2.9
28,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,6,pm10,151,2022,1,1,2022-01-01 06:00:00,5.6,77.0,1.9
29,2022-01-01,01cf1cec-bf2d-41b3-8cd5-e8bd720f01b4,7,pm10,170,2022,1,1,2022-01-01 07:00:00,6.0,74.0,5.2

In [25]:
df_pm10_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1209199 entries, 0 to 1209198
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   date         1209199 non-null  object
 1   sensor_id    1209199 non-null  object
 2   hour         1209199 non-null  int64
 3   type         1209199 non-null  object
 4   value        1209199 non-null  int64
 5   year         1209199 non-null  int64
 6   month        1209199 non-null  int64
 7   day          1209199 non-null  int64
 8   timestamp    1209199 non-null  datetime64[ns]
 9   temperature  1158739 non-null  float64
 10  humidity     1158739 non-null  float64
 11  wind_speed   1158739 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(5), object(3)
memory usage: 110.7+ MB

In [26]:
df_pm10_merged.shape

(1209199, 12)

In [27]:
df_pm10_merged[(df_pm10_merged['temperature'].isnull()) | (df_pm10_merged['humidity'].isnull()) | (df_pm10_merged['wind_speed'].isnull())].shape

(50460, 12)

In [28]:
df_pm10_merged.dropna(inplace=True)

In [29]:
df_pm10_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1158739 entries, 0 to 1209131
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   date         1158739 non-null  object
 1   sensor_id    1158739 non-null  object
 2   hour         1158739 non-null  int64
 3   type         1158739 non-null  object
 4   value        1158739 non-null  int64
 5   year         1158739 non-null  int64
 6   month        1158739 non-null  int64
 7   day          1158739 non-null  int64
 8   timestamp    1158739 non-null  datetime64[ns]
 9   temperature  1158739 non-null  float64
 10  humidity     1158739 non-null  float64
 11  wind_speed   1158739 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(5), object(3)
memory usage: 114.9+ MB

In [30]:
df_pm2_5_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1198979 entries, 0 to 1198978
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   date         1198979 non-null  object
 1   sensor_id    1198979 non-null  object
 2   hour         1198979 non-null  int64
 3   type         1198979 non-null  object
 4   value        1198979 non-null  int64
 5   year         1198979 non-null  int64
 6   month        1198979 non-null  int64
 7   day          1198979 non-null  int64
 8   timestamp    1198979 non-null  datetime64[ns]
 9   temperature  1149050 non-null  float64
 10  humidity     1149050 non-null  float64
 11  wind_speed   1149050 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(5), object(3)
memory usage: 109.8+ MB

In [32]:
df_pm2_5_merged[(df_pm2_5_merged['temperature'].isnull()) | (df_pm2_5_merged['humidity'].isnull()) | (df_pm2_5_merged['wind_speed'].isnull())].shape

(49929, 12)

In [33]:
df_pm2_5_merged.dropna(inplace=True)

In [34]:
df_no2_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47295 entries, 0 to 47294
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         47295 non-null  object
 1   sensor_id    47295 non-null  int64
 2   hour         47295 non-null  int64
 3   type         47295 non-null  object
 4   value        47295 non-null  int64
 5   year         47295 non-null  int64
 6   month        47295 non-null  int64
 7   day          47295 non-null  int64
 8   timestamp    47295 non-null  datetime64[ns]
 9   temperature  45182 non-null  float64
 10  humidity     45182 non-null  float64
 11  wind_speed   45182 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(6), object(2)
memory usage: 4.3+ MB

In [35]:
df_no2_merged[(df_no2_merged['temperature'].isnull()) | (df_no2_merged['humidity'].isnull()) | (df_no2_merged['wind_speed'].isnull())].shape

(2113, 12)

In [36]:
df_no2_merged.dropna(inplace=True)

In [37]:
df_pm10_merged.to_csv('Data/pm10_with_weather.csv', index=False)
df_pm2_5_merged.to_csv('Data/pm2_5_with_weather.csv', index=False)
df_no2_merged.to_csv('Data/no2_with_weather.csv', index=False)